find_path(NVPIPE_INCLUDE_DIR NAMES NvPipe.h PATHS ${CONAN_INCLUDE_DIRS_NVPIPE})
find_library(NVPIPE_LIBRARY NAMES ${CONAN_LIBS_NVPIPE} PATHS ${CONAN_LIB_DIRS_NVPIPE})

MESSAGE("** NVPIPE ALREADY FOUND BY CONAN!")
SET(NVPIPE_FOUND TRUE)
MESSAGE("** FOUND NVPIPE:  ${NVPIPE_LIBRARY}")
MESSAGE("** FOUND NVPIPE INCLUDE:  ${NVPIPE_INCLUDE_DIR}")

set(NVPIPE_INCLUDE_DIRS ${NVPIPE_INCLUDE_DIR})
set(NVPIPE_LIBRARIES ${NVPIPE_LIBRARY})

mark_as_advanced(NVPIPE_LIBRARY NVPIPE_INCLUDE_DIR)

if(NVPIPE_INCLUDE_DIR AND EXISTS "${NVPIPE_INCLUDE_DIR}/NvPipe.h")
    file(STRINGS "${NVPIPE_INCLUDE_DIR}/NvPipe.h" NVPIPE_H REGEX "^#define NVPIPE_VERSION \"[^\"]*\"$")

    # should be defined in library.
    set(NVPIPE_VERSION_MAJOR 0)
    set(NVPIPE_VERSION_MINOR 1)
    set(NVPIPE_VERSION_PATCH 0)

    set(NVPIPE_VERSION_STRING "${NVPIPE_VERSION_MAJOR}.${NVPIPE_VERSION_MINOR}.${NVPIPE_VERSION_PATCH}")
    set(NVPIPE_MAJOR_VERSION "${NVPIPE_VERSION_MAJOR}")
    set(NVPIPE_MINOR_VERSION "${NVPIPE_VERSION_MINOR}")
    set(NVPIPE_PATCH_VERSION "${NVPIPE_VERSION_PATCH}")
endif()